travis:
  secure:
    BINSTAR_TOKEN: QFWZ4XuyNjnLeY2h1gEZzlUUu1y5eM7uHP0Zm8u8QICVb1PS4IfinpVuFYzuUxwyx/TGIJEWnz9+uHryQAcZsL2tQFUHMpptRe4d7fmBTlzEA9FhJOMxoziXnDH5y2+Uue+xKMC65HWbRQ7KnrFk4CGfeWXW+f0W6MT/0gjWIM0p2jDRiNsfZQqbjchrDxrD4sWZOHZ48AqUJVauHqknuk8tqx9HW0gQH3qpjup95NG98BYPqSsAtjf9X27cBE88RgdhuqHvCP4bFP5F1zAgUdah1gTqeEB4ZVbDTLk0WCTzWsTM40ApFgJYyiQ2QrIKXc8he8mGv/MiWLaBfp5st5sYVp3858tODHtK4p2b8Iys4KP8TrLEx5EFZ8k2tsPi2jVbei3IAjYua4I/P0jsnS+lrAeqgtJxblV4u7EZD+RaIYCa4VABLbOoH2hcKFiu4wdcSNiVW8WvvjcDVRX87ScZGlUep5XJaJYe2+KbJnyIoAqa1QPOhnOXbCE2fCtWwUAvw3ubX6r3LtSMQOGRldBCGoXy2noMfXmjS8AQc2KuKb8RnBHmUY+j3XLCIuZYpLSa5Ffp8xZIq0x+lq6LRdVfRNNuSvdxyerNKr3L9tljv+HIYFRZ9VVRbnZ8LX06epT9IsT1w4C/t3Jh6QkIYoX+omcjzPpT4sRMKjN3FJM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
