travis:
  secure:
    BINSTAR_TOKEN: YVzkWocscpB34VP4uTiV/dqJEKCEtmvTGO80SCihV/kMQQr5p337yiXZUtf3VNoEBKfnH5Y2btUxTJW7IrNiO7srFs3Nd8Ch5U5ta8f5ZKrWGY648Ou3PTguQC4NAQqqLzYMxMEdXlGmAzw9t6RyAHkzU8v3fbn380fPRb4+ZbTdWEGOaEZEDDkmErVH8uWE/FCzf6IXzP340rfOj7hc5TgrKBGyO+cTY89SZF+sZ97m/hcE5Z/lCC7LczQW+C6v/NJuUhzs52Blmb7bTwF+JrQpR7ggoNajFGrtTgxFzaH0h6gUCxYDAZYNyQ37rVZ38cv9ZJfHmpQ29y5wYWVt349tkYgQg6M4ApiBIJFjdANI/ukrY1kWm3oSmyn9w962CA52j1wdm3sbJqMJ/XYZ7VAzqCWPYuB0JRC6P/p4AiUvsUEpS2vwq8hYMth/LnZIb4PBNogBsz6RgW9ePaGHwzov5MWoGF9UDn82w6Dd/JC7f3VK1zsXBbJRmjBrNmcpeDoXSGwRv8mbgaKp5YE0PmAG80WV7Jjbp5rXLz0uUXabTM4NN0MQQGOmPT+t+z5auYWqG4NXDCAutNndVaICH3KCMlRXmzJ1SF0v57XIta+L3B+JTDWXZec3QZfY9qFVFDPblLo5NC0bQeimyPpPGiGR7xqDZg8BRhcr8A0areo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
